### PR TITLE
Other PRs combined with support for more signatures

### PR DESCRIPTION
**Pull request by th0rgall**
Hi! At [Welcome To My Garden](https://github.com/WelcometoMyGarden/welcometomygarden) we've been running this library in production for some months now, for experimental chat email reply support. I've been monitoring how it's performing in detail.

It parses ~90% of our incoming email properly, so thanks for that!

For the remaining ~10% of problematic parse results, some issues were already fixed by other PRs (#24, #21 and #20). I have merged these into our fork.

I've also added several more fixes, all related to the signature regexes.

**I'm not asking/expecting this PR to be merged as-is, as I see the previous PR's haven't been reviewed yet.** 

I'm mostly opening this to call attention to our fork, so that other package consumers can conveniently find and use it for the time being. I'll try to maintain this fork as I see new issues popping up.

I'd be happy to rework this PR to just include (a subset) of my own fixes, or into multiple PRs, to make it mergeable next to the other PRs.

### CODE REVIEW

**Comment by baptistejamin** [comment]
Thank you so much for your PR.

I will review everything and merge as much as possible.

**Comment by baptistejamin** [comment]
So we would like to avoid RegExp. Reason is RexExp is prone to ReDOS attacks, for this reason we rely on RE2.

**Comment by baptistejamin** [comment]
Hey!

I adapted your PR with the other merges we got!

Thank you so much

**Comment by th0rgall** [comment]
Thanks for the quick review & the new release! 🥳 

> So we would like to avoid RegExp. Reason is RexExp is prone to ReDOS attacks, for this reason we rely on RE2.

I understand that, but I believe the commits didn't introduce any new vulnerability? Please correct me if I'm wrong.

I used the RegExp constructor to avoid repeating a constant sub-expression 4x or 3x, which isn't possible with the `/.../` syntax. The RegExp objects were all still being passed through the `buildRe2` function, and became re2 expressions just like the other `/.../` regex expression inputs.  As far as I know, `/.../` is just a ["syntactic sugar" alternative](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_expressions#creating_a_regular_expression) to `new RegExp("...")`, differing only in the way in which backslashes and quotes are escaped. RegExp wasn't used anywhere directly.

Whether this was a premature _don't-repeat-yourself_ intervention is of course your call 🙂 I'll try to follow the existing style if I suggest any more changes.

**Comment by baptistejamin** [comment]
I am totally on the same page about the Don't repeat yourself, but we got many issues at Crisp with RegExp and ReDOS especially with this package.

Since most regexes are crowdsourced and PRs, keeping the stuff simple, but not DRY is the best way here to simplify collaboration and in the meantime, avoid ReDOS.

**Pull request closed without merging**
